# Generated by Django 3.2.8 on 2023-08-21 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_emailverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.CharField(default=datetime.datetime(2023, 8, 21, 15, 22, 16, 10775, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
