# Generated by Django 3.2.8 on 2023-08-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='cls',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BCOM', 'BCOM'), ('MCOM', 'MCOM'), ('BA', 'BA'), ('MA', 'MA'), ('DIPLOMA', 'DIPLOMA'), ('ENGINEERING', 'ENGINEERING')], max_length=50),
        ),
    ]
