# Generated by Django 3.2.8 on 2023-08-24 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_studentprofile_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='img',
            field=models.ImageField(default=datetime.datetime(2023, 8, 24, 14, 11, 37, 849300, tzinfo=utc), upload_to='pro_img'),
            preserve_default=False,
        ),
    ]
