# Generated by Django 3.2.8 on 2023-08-27 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_studentprofile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Commerce', 'Commerce'), ('Computer Science', 'Computer Science'), ('Science', 'Science'), ('Arts', 'Arts')], max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('img', models.ImageField(upload_to='lec_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
