# Generated by Django 3.2.8 on 2023-08-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_assignments_valued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='assignments'),
        ),
    ]
